version: '3.4'

networks:
  backend:

services:
  RedarborDB:
    container_name: Redarbor-DB
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password@12345#
    networks:
        - backend
    ports:
        - 8001:1433 
  redarbortechnicaltest.api:
    container_name: redarbortechnicaltest-api
    image: ${DOCKER_REGISTRY-}redarbortechnicaltestapi
    build:
      context: .
      dockerfile: RedarborTechnicalTest.Api/Dockerfile
    networks:
        - backend
    ports:
        - 8002:80 
    environment:
        - DB_HOST=RedarborDB
        - DB_NAME=EMPLOYEE
        - DB_SA_PASSWORD=password@12345#


