version: '3.4'

networks:
  backend:

services: 
  redarbortechnicaltest.api:
    container_name: redarbortechnicaltest-api
    image: ${DOCKER_REGISTRY-}redarbortechnicaltestapi
    build:
      context: .
      dockerfile: RedarborTechnicalTest.Api/Dockerfile
    networks:
        - backend
    ports:
        - 8002:80 
    environment:
        - DB_HOST=microservices-test-david.database.windows.net
        - DB_NAME=RedarborDB
        - DB_SA_USER=microservices1028
        - DB_SA_PASSWORD=Prueba1234.


